### ISSUE TITLE
关于您文中提到有关于比特派的回复

### ISSUE THREAD

**Issue by bitpiedotcom** [blockchainer2/mytoken#1]
关于您文中提到有关于比特派的部分作出以下回复：

一、关于地址 0x91c9向比特派0x48fc（Bitpie: Deployer）转账 1ETH 的说明

0x91c9 地址曾使用过比特派钱包的公开服务 “Token 工厂” 来创建 ERC20 Token，创建 token 名称为：66Cash ，合约地址为：0x1466734D94f99867189bD76162B41256fe4562F2

1ETH 为 Token 工厂的使用费，相关功能可在 比特派APP首页——更多——Token 工厂 查看。

二、关于合约 bytecode 完全一样的说明

所有通过 Token 工厂创建的 ERC20 合约代码（bytecode）都是一样的，只是在部署合约时传的参数（token 信息）不同而创建出的 token 不同，也就是说所有使用 Token 工厂创建的合约 bytecode 全是一样的。

Token 工厂从上线至今已经有相当多的用户创建了自己的 token，这些 token 的 bytecode 都是一样的，etherscan 区块浏览器上可以查到 bytecode 相同的合约，您可以通过下面的链接查到这些 similar contracts，这些合约的 bytecode 均相同，只不过是 token 的参数不同：
https://cn.etherscan.com/find-similar-contracts?a=0x22b1028bffe5a53c3fc56737562ab34fe8da129f

三、如您遇到盗币事件，建议尽快报警，通过司法途径找到盗币者，以帮助您找回被盗资产。

**Comment by blockchainer2** [comment]
> bitpiedotcom

Thank you for your reply.  I see what happened.
